keys:
  - &asgard age1uqltjql96ttngvw4peylxtg2fnkgtlqxld9naeda34mp9l3zf3jsndncy5
  - &baldur-biche age1aur8v0sdutdvw2lagwh4mw0gxdhxeqgypucmdatpmtns0jgw798q5394zd
  - &baldur-root age1qva0v8ka9pnh748fswd60y52luum5hthf7t5fh483xm7wn5al5hslejace
  - &baldur-robot age1q6a6qcuczj26e900mh4she2n0ezlze0297usjarpddzvdhst7yhshg9cds
  - &heimdall age1jvc7p6m0dz8a2p8k8yv38z94a50sypsunpnxg7w4mfm565vv3caqwumktk
  - &midgard-ops age17zv30v64zrxslhtkzc8qzguwyrzlryk9a2c55m4fmguhrjz8fsjsc3pycx
  - &midgard-root age15qjtky92e0m33zld0mp2z9jenefgk2ems95au9537eey4udvsauq6kxl9v
  - &njord age1n78wzny3xlzukd8m09jr589sn95fwz3ug65wu7408cymx0unn9ssgrwkz6
  - &njord-host age1wsdqdexlqzmzs8muh8t4rvxhudn4eentw0jp2mtk0ftm4p4yesfqj72kfs
  - &robot age1dtjtjdg8dpe3xq7amg3u2v6ga0srl4x7nflznvtx2h9czw9qea8q7pypqp
  - &spare age13aaym2awn8zgz4zrt5dscyy6wcc5z2ntt8tfm8syflde0djqka4q5sncmg
  - &yggdrasil-ops age154vpafvshynw9jwp6gkege9eph8jwspfch3sd8vcuq2rt00zv50s4y806k
  - &yggdrasil-root age1jmazcskxhmlcv5ne4mvu98crszu7ptg3q5kgcp53ck6pfsjeng8qz7vf7w
  - &vili age15p5yhymr8u29jlxhrwx40fmmdrswqc65fxnk0va59cf8z0clkq9s78fz0j
creation_rules:
  - path_regex: secrets/.*\.(yaml|json)$
    key_groups:
      - age:
        - *asgard
        - *baldur-biche
        - *baldur-root
        - *baldur-robot
        - *heimdall
        - *midgard-ops
        - *midgard-root
        - *njord
        - *njord-host
        - *robot
        - *spare
        - *yggdrasil-ops
        - *yggdrasil-root
        - *vili
