[widget.control-center]
custom_image = "~/nixfiles/modules/home/hyprland/nixos-logo.png"
custom_image_colorize = false

[widget.clock]
format = "{:%H:%M}"

[widget.cpu]
type       = "sysmon"
stat       = "cpu_usage"
visualization = "graph"
show_value    = false

[widget.cpu_temp]
type       = "sysmon"
stat       = "cpu_temp"
visualization = "graph"
show_value    = true

[widget.gpu_temp]
type       = "sysmon"
stat       = "gpu_temp"
visualization = "graph"
show_value    = true

[widget.mem]
type       = "sysmon"
stat       = "ram_used"
visualization = "graph"
show_value    = false

[widget.disk]
type = "sysmon"
stat = "disk_free"
path = "/"
visualization = "graph"
show_value    = false

[widget.network]
show_label = false

[widget.keyboard_layout]
hide_when_single_layout = false
show_glyph = true
show_label = false
display = "short"   # short | full
