set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on


unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Vim like pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Change from 0 based to 1 based because keyboard layout
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Vim-like copy/paste
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Alt+hjkl to switch panes (vim-style)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Alt+number to select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind-key -r f run-shell "tmux-switcher"
bind-key -n M-y run-shell "tmux-switcher ~/src/homelab"
bind-key -n M-u run-shell "tmux-switcher ~/nixfiles"
bind-key -n M-i run-shell "tmux-switcher ~/src/nixos-apple-silicon"
bind-key -n M-o run-shell "tmux-switcher ~/src/nixpkgs"
bind -n Insert next-window

# Nord Dark theme colors
thm_nord0="#2e3440"
thm_nord1="#3b4252"
thm_nord2="#434c5e"
thm_nord3="#4c566a"
thm_nord4="#d8dee9"
thm_nord5="#e5e9f0"
thm_nord6="#eceff4"
thm_nord7="#8fbcbb"
thm_nord8="#88c0d0"
thm_nord9="#81a1c1"
thm_nord10="#5e81ac"
thm_nord11="#bf616a"
thm_nord12="#d08770"
thm_nord13="#ebcb8b"
thm_nord14="#a3be8c"
thm_nord15="#b48ead"

# Status bar
set -g status "on"
set -g status-bg "${thm_nord1}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# Messages
set -g message-style "fg=${thm_nord8},bg=${thm_nord3},align=centre"
set -g message-command-style "fg=${thm_nord8},bg=${thm_nord3},align=centre"

# Panes
set -g pane-border-style "fg=${thm_nord3}"
set -g pane-active-border-style "fg=${thm_nord10}"

# Windows
set -g window-status-activity-style "fg=${thm_nord6},bg=${thm_nord1},none"
set -g window-status-separator ""
set -g window-status-style "fg=${thm_nord6},bg=${thm_nord1},none"

# Statusline - current window
set -g window-status-current-format "#[fg=${thm_nord10},bg=${thm_nord1}] #I: #[fg=${thm_nord15},bg=${thm_nord1}](✓) #[fg=${thm_nord8},bg=${thm_nord1}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=${thm_nord15},bg=${thm_nord1}]"

# Statusline - other windows
set -g window-status-format "#[fg=${thm_nord10},bg=${thm_nord1}] #I: #[fg=${thm_nord6},bg=${thm_nord1}]#W"

# Statusline - right side
set -g status-right "#[fg=${thm_nord10},bg=${thm_nord1},nobold,nounderscore,noitalics]#[fg=${thm_nord1},bg=${thm_nord10},nobold,nounderscore,noitalics] #[fg=${thm_nord6},bg=${thm_nord3}] #(hyprctl activeworkspace -j | jq -r .name) #{?client_prefix,#[fg=${thm_nord14}],#[fg=${thm_nord8}]}#[bg=${thm_nord3}]#{?client_prefix,#[bg=${thm_nord14}],#[bg=${thm_nord8}]}#[fg=${thm_nord1}] #[fg=${thm_nord6},bg=${thm_nord3}] #S #[fg=${thm_nord14},bg=${thm_nord3},nobold,nounderscore,noitalics]#[fg=${thm_nord1},bg=${thm_nord14}]󰁹 #[fg=${thm_nord6}, bg=${thm_nord3}] #(acpi | awk '{ print $4 }' | tr , ' ')#[fg=${thm_nord12},bg=${thm_nord3},nobold,nounderscore,noitalics]#[fg=${thm_nord1},bg=${thm_nord12}]⏱️ #[fg=${thm_nord6},bg=${thm_nord3}] %H:%M "

# Statusline - left side (empty)
set -g status-left ""

# Modes
set -g clock-mode-colour "${thm_nord10}"
set -g mode-style "fg=${thm_nord10} bg=${thm_nord4} bold"

