{
  host,
  self,
  ...
}:
{
  imports = [
    "${self}/hosts/${host}"
    "${self}/modules/common"
    ./arr.nix
    ./audio.nix
    ./binary-cache.nix
    ./boot.nix
    ./desktop
    ./dns-server.nix
    ./home-assistant.nix
    ./immich.nix
    ./impermanence.nix
    ./kids.nix
    ./media-player.nix
    ./networking.nix
    ./podman.nix
    ./reverseProxy.nix
    ./samba.nix
    ./security.nix
    ./gaming.nix
    ./storage.nix
    ./system.nix
    ./tailscale.nix
    ./ups.nix
    ./users.nix
    ./virtualization
    ./wireguard.nix
    ./zfs.nix
  ];
}
