{ host, inputs, self, ... }:
{
  imports = [
    "${inputs.nixpkgs}/nixos/modules/hardware/video/displaylink.nix"
    "${self}/hosts/${host}"
    "${self}/modules/common"
    ./arr.nix
    ./audio.nix
    ./boot.nix
    ./desktop
    ./dns-server.nix
    ./home-assistant.nix
    ./immich.nix
    ./media-player.nix
    ./networking.nix
    ./podman.nix
    ./reverseProxy.nix
    ./samba.nix
    ./security.nix
    ./sops.nix
    ./steam.nix
    ./storage.nix
    ./system.nix
    ./tailscale.nix
    ./ups.nix
    ./users.nix
    ./virtualization.nix
  ];
}
